### ISSUE TITLE
需要提取文本特征，关于传入的text_file="input.txt"问题

### ISSUE THREAD

**Issue by Chi-Tian** [thuiar/MMSA-FET#15]
您好，需要提取文本特征，传入的text_file="input.txt"，这个input.txt文件是什么样的，是否是label.csv文件中text那一列转存为.txt文件？
我按照上面做法尝试，结果将所有的文本当成一个字符串传入BERT，会显示维度不匹配。
请问您是如何定义哪个text_file文件的，还望您在空闲时回复，谢谢！

**Comment by FlameSky-S** [comment]
run_single函数的参数text_file传入的文件为单行文本

**Comment by Chi-Tian** [comment]
> run_single函数的参数text_file传入的文件为单行文本，仅包含raw_text即可

好的，非常感谢！
