### ISSUE TITLE
关于提取数据集中的音频特征

### ISSUE THREAD

**Issue by zywang98** [thuiar/MMSA-FET#4]
你好，我在使用这个工具包提取SIMS这个数据集的音频特征的时候，如果仅提取单个视频的特征，是能够正确的print，但是在导入数据集批量提取的时候，没有办法正确提取，显示“error occurred when extracting features for video，ignore error and continue，see the log for details”，最后输出的audiofeature也只有910b，请问这个log for details文件怎样查看呢，麻烦您指导一下我该怎么处理这个问题~

**Comment by FlameSky-S** [comment]
您好，默认的日志文件在`~/.MMSA-FET/log`文件夹内。您看一下是否有具体的错误信息

**Comment by zywang98** [comment]
鞠躬感谢！文件找到了，祝您以及您的团队科研顺利~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thuiar/MMSA-FET"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月21日(星期六) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thuiar/MMSA-FET] 关于提取数据集中的音频特征 (Issue #4)





 
您好，默认的日志文件在~/.MMSA-FET/log文件夹内。您看一下是否有具体的错误信息
