### ISSUE TITLE
关于COVAREP配置文件的请求

### ISSUE THREAD

**Issue by chenjunyi1999** [thuiar/MMSA-FET#8]
您好，最近刚接触多模态，发现很多开源数据集在音频特征提取上都使用了COVAREP来提取74维的特征。由于COVAREP已经停止跟新且自己对matlab不熟悉，想自己复现COVAREP的特征提取有些困难。请问是否可以提供一个利用librosa/opensmile的config来实现COVAREP。非常感谢！

**Comment by FlameSky-S** [comment]
您好，librosa与COVAREP在计算一些特征时（例如MFCC）似乎有些不同，建议您使用原始的COVAREP脚本来提取特征。在Python中可以用`oct2py`库来运行MATLAB的.m文件。参考[这里](https://pypi.org/project/oct2py/#:~:text=To%20run%20.m%20function%2C%20you%20need%20to%20explicitly%20add%20the%20path%20to%20.m%20file%20using%3A)。

**Comment by chenjunyi1999** [comment]
非常感谢！
